:_mod-docs-content-type: CONCEPT

[id="con-azure-maintenance-upgrade_{context}"]

= Product lifecycle and maintenance 

Understand the version lifecycle, planned upgrade windows, uptime policy, and support coverage for {AAPonAzureName}.

== Version lifecycle

{PlatformName} on {Azure} employs a continuous release approach to versioning, meaning that customers are upgraded to the latest version that Red Hat supports on a cadence that Red Hat defines. {PlatformNameShort} on Azure cannot be version locked for customers at this time.

As a managed application, Red Hat provides upgrades to the offering as per the cadence defined below to deliver modern application features, product fixes, and security updates.

[cols="a,a,a"]
|===
| {PlatformNameShort} on Azure Packaging | {PlatformNameShort} | Seeded content
| Continuously Released outside of {PlatformNameShort} version | Updated to maintain cadence with the most recently published version of {PlatformNameShort} (x.y.z release streams) | Continuously Released outside of {PlatformNameShort} version
|===

== Planned upgrade windows

Red Hat has defined windows in which upgrades occur, and those windows may change over time in an effort to improve service offerings. Every effort is taken to reduce or eliminate any downtime during these windows. However, these windows are provided to allow for system downtime should it be required.

In the cases where operations require more time than the planned window, then the operation time has precedence over the defined window time. The "upgrade window" timeline is not synonymous with an expected outage timeline; it defines the time over which upgrades are planned to occur.

[cols="a,a,a,a"]
|===
| Cadence | Expected upgrade window | Time | Purpose
| Ad hoc | N/A | As needed for security | Critical CVE patches
| Daily | 1 hour | 2:00am ET | CVE patches
| Weekly | 2 hours| 2AM ET | {PlatformNameShort} and infrastructure upgrades (North American deployments).
| Weekly | 2 hours| 2AM UTC | {PlatformNameShort} and infrastructure upgrades (EMEA deployments).
| Weekly | 2 hours| 2AM JST | {PlatformNameShort} and infrastructure upgrades (APAC deployments).
| Ad hoc | 1 hour | 2am UTC Sunday | Azurre Database for PostgreSQL flexible server.
| Ad hoc | 4 hour | 2am UTC Sunday | AKS cluster node operating system updates. 
|===

[NOTE]
====
These windows are only a guidance, and Red Hat reserves the ability to perform platform operations as needed to maintain the health of Ansible on Azure deployments.
====

== Uptime policy
As a managed application, Red Hat strives to limit any solution downtime. Red Hat has a team of _Site Reliability Engineers_ (SREs) dedicated to {AAPonAzureName} to provide monitoring and cloud offering support. However, there is no current uptime guarantee for {AAPonAzureNameShort}. Due to the nature of managed applications, such as resources running on a third-party provider ({Azure}), there might be circumstances that cause downtime that are outside of Red Hat control. Red Hat works closely with Microsoft to deliver a stable and reliable solution.

=== Scope of coverage
Support is provided for use according to the published Scope of Coverage in Appendix 1 of the link:https://www.redhat.com/en/about/enterprise-agreements[Red Hat Enterprise Agreement].
As a managed application, Red Hat supports the managed application as currently deployed to customers. Versions that are not actively in use by {AAPonAzureNameShort} are not supported.



